global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.Extensions.Logging;
global using global::Microsoft.Extensions.Configuration.Json;
global using global::Microsoft.Extensions.Configuration.CommandLine;
global using global::Microsoft.Extensions.Configuration.EnvironmentVariables;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;
// <auto-generated/>
global using global::Wpf.Extensions.Hosting;
